[package]
name = "stacked_errors"
version = "0.7.1"
edition = "2021"
# when updating, update `rust-msrv` in flake.nix and `msrv_test_suite` in ci.yml, and separately
# bump rust-toolchain.toml
rust-version = "1.81"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AaronKutch/stacked_errors"
documentation = "https://docs.rs/stacked_errors"
categories = ["data-structures", "no-std"]
keywords = ["error", "error-handling", "stacked-errors", "no_std"]
description = "high level error propogation with software controlled backtraces"

[features]
default = []

[dependencies]
owo-colors = { version = "4.1", default-features = false }
smallbox = { version = "0.8", default-features = false }
thin-vec = { version = "0.2", default-features = false }
thiserror = { version = "2", default-features = false }

[dev-dependencies]
ron = { version = "0.12", default-features = false }
serde_json = { version = "1.0" }
