[package]
name = "stacked_errors"
version = "0.3.0"
edition = "2021"
# change the test suite version when changing this
rust-version = "1.69"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AaronKutch/stacked_errors"
documentation = "https://docs.rs/stacked_errors"
keywords = ["error", "error-handling", "stacked-errors"]
description = "experimental error type"

[dependencies]
thin-vec = "0.2"
thiserror = "1.0"

[dev-dependencies]
ron = { version = "0.8", default-features = false }

[features]
default = []
