[package]
name = "stacked_errors"
version = "0.1.0"
edition = "2021"
rust-version = "1.69"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AaronKutch/stacked_errors"
documentation = "https://docs.rs/stacked_errors"
keywords = ["error", "error-handling", "stacked-errors"]
description = "experimental error type"

[dependencies]
ctrlc = { version = "3.0", optional = true, default-features = false }
env_logger = { version = "0.10", optional = true, default-features = false }
ron = { version = "0.8", optional = true, default-features = false }
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.9", optional = true }
thiserror = "1.0"
tokio = { version = "1.28", optional = true, default-features = false, features = ["rt"] }
toml = { version = "0.7", optional = true }

[features]
default = [
    "tokio_rt_support",
    "serde_json_support",
    "ron_support",
    "ctrlc_support",
    "env_logger_support",
    "toml_support",
    "serde_yaml_support",
]
tokio_rt_support = ["tokio"]
serde_json_support = ["serde_json"]
ron_support = ["ron"]
ctrlc_support = ["ctrlc"]
env_logger_support = ["env_logger"]
toml_support = ["toml"]
serde_yaml_support = ["serde_yaml"]
